name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pre-Install Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Packages
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test

      - name: Verify Dockerfiles updates
        uses: tj-actions/changed-files@v41
        id: changed-dockerfiles
        with:
          files: |
            Dockerfile

      - name: Validate Backend Docker Image build - if updated
        if: contains(steps.changed-dockerfiles.outputs.modified_files, 'Dockerfile')
        run: |
          echo "Test Docker build step"
          cp ${NPM_CONFIG_USERCONFIG} .npmrc
          docker build --build-arg NPMRC=".npmrc" --build-arg NODE_AUTH_TOKEN="${{ github.token }}" --pull -f Dockerfile -t build:back .
          echo "Validate Image was created"
          docker images build:back
          echo "Remove test image"
          docker rmi build:back